variables:
  moduleName: Cloudmarque.Azure
  environment: Integration

pool:
  vm-image: windows-latest

stages:

- stage: Core
  jobs:
  - job:
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: $(ServiceConnection)
        workingDirectory: $(Build.SourcesDirectory)
        pwsh: true
        errorActionPreference: Stop
        ScriptType: InlineScript
        FailOnStandardError: true
        azurePowerShellVersion: 'LatestVersion'
        Inline: |

          ./Initialise-Cloudmarque.ps1 `
            -ProjectDirectory "$(Build.SourcesDirectory)" `
            -Environment "$(environment)" `
            -BuildNumber "$(Build.BuildNumber)" `
            -RepositoryName "$(Build.Repository.Name)" `
            -DefinitionName "$(Build.DefinitionName)" `
            -DefinitionVersion "$(Build.DefinitionVersion)"

          New-CmazCore -SettingsFile "$(Build.SourcesDirectory)/$(moduleName)/Resources/Project/core.yml" -Verbose

- stage: Paas
  dependsOn: Core
  jobs:
  - job:
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: $(ServiceConnection)
        workingDirectory: $(Build.SourcesDirectory)
        pwsh: true
        errorActionPreference: Stop
        ScriptType: InlineScript
        FailOnStandardError: true
        azurePowerShellVersion: 'LatestVersion'
        Inline: |

          ./Initialise-Cloudmarque.ps1 `
            -ProjectDirectory "$(Build.SourcesDirectory)" `
            -Environment "development" `
            -BuildNumber "$(Build.BuildNumber)" `
            -RepositoryName "$(Build.Repository.Name)" `
            -DefinitionName "$(Build.DefinitionName)" `
            -DefinitionVersion "$(Build.DefinitionVersion)"

          # Below resources are not being deployed because of known cdn api issue with Set-AzResource in Set-CmAzTag
          # New-CmazPaasWeb -SettingsFile "$(Build.SourcesDirectory)/$(moduleName)/Resources/Project/web.yml" -Verbose
          # New-CmazPaasWebStatic -SettingsFile "$(Build.SourcesDirectory)/$(moduleName)/Resources/Project/webstatic.yml" -Verbose
          New-AzResourceGroup -Name "Web-Test-Rg" -location uksouth -tag @{'cm-service' = "Web-Test-Rg"; 'cm-integration-test-delete' = "true" } -Force
          New-CmazPaasSql -SettingsFile "$(Build.SourcesDirectory)/$(moduleName)/Resources/Project/sql.yml" -Verbose

- stage: Iaas
  dependsOn: Core
  jobs:
  - job: IaasNetwork
    displayName: Iaas - Networking
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: $(ServiceConnection)
        workingDirectory: $(Build.SourcesDirectory)
        pwsh: true
        errorActionPreference: Stop
        ScriptType: InlineScript
        FailOnStandardError: true
        azurePowerShellVersion: 'LatestVersion'
        Inline: |

          ./Initialise-Cloudmarque.ps1 `
            -ProjectDirectory "$(Build.SourcesDirectory)" `
            -Environment "$(environment)" `
            -BuildNumber "$(Build.BuildNumber)" `
            -RepositoryName "$(Build.Repository.Name)" `
            -DefinitionName "$(Build.DefinitionName)" `
            -DefinitionVersion "$(Build.DefinitionVersion)"

          New-CmAzIaasStorage -SettingsFile "$(Build.SourcesDirectory)/$(moduleName)/Resources/Project/storage.yml" -Verbose

          New-CmAzIaasNetworking `
              -VnetsCsvFile "$(Build.SourcesDirectory)/$(moduleName)/Resources/Project/networking/csv/vnet.csv" `
              -RouteTablesCsvFile "$(Build.SourcesDirectory)/$(moduleName)/Resources/Project/networking/csv/udr.csv" `
              -NsgsCsvFile "$(Build.SourcesDirectory)/$(moduleName)/Resources/Project/networking/csv/nsg.csv" `
              -Verbose `
              -Confirm:$false

  - job: IaasVmPatchVault
    dependsOn: IaasNetwork
    displayName: Iaas - Vms, Recovery Vaults and Patching
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: $(ServiceConnection)
        workingDirectory: $(Build.SourcesDirectory)
        pwsh: true
        errorActionPreference: Stop
        ScriptType: InlineScript
        FailOnStandardError: true
        azurePowerShellVersion: 'LatestVersion'
        Inline: |

          ./Initialise-Cloudmarque.ps1 `
            -ProjectDirectory "$(Build.SourcesDirectory)" `
            -Environment "$(environment)" `
            -BuildNumber "$(Build.BuildNumber)" `
            -RepositoryName "$(Build.Repository.Name)" `
            -DefinitionName "$(Build.DefinitionName)" `
            -DefinitionVersion "$(Build.DefinitionVersion)"

          New-CmAzIaasVm `
            -SettingsFile "$(Build.SourcesDirectory)/$(moduleName)/Resources/Project/virtualmachines.yml" `
            -LocalAdminUsername (ConvertTo-SecureString $(AdminUsername) -AsPlainText -Force) `
            -LocalAdminPassword (ConvertTo-SecureString $(AdminPassword) -AsPlainText -Force) `
            -Verbose

          New-CmAzIaasRecoveryServicesVault `
            -SettingsFile "$(Build.SourcesDirectory)/$(moduleName)/Resources/Project/recoveryvault.yml" `
            -PolicySettingsFile "$(Build.SourcesDirectory)/$(moduleName)/Resources/Project/recoverypolicy.yml" `
            -Verbose

          Set-CmAzIaasUpdateManagement -SettingsFile "$(Build.SourcesDirectory)/$(moduleName)/Resources/Project/updateManagement.yml" -Verbose

  - job: IaasBastionVPN
    dependsOn: IaasNetwork
    displayName: Iaas - Bastion Host and VPN Gateway
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: $(ServiceConnection)
        workingDirectory: $(Build.SourcesDirectory)
        pwsh: true
        errorActionPreference: Stop
        ScriptType: InlineScript
        FailOnStandardError: true
        azurePowerShellVersion: 'LatestVersion'
        Inline: |

          ./Initialise-Cloudmarque.ps1 `
            -ProjectDirectory "$(Build.SourcesDirectory)" `
            -Environment "$(environment)" `
            -BuildNumber "$(Build.BuildNumber)" `
            -RepositoryName "$(Build.Repository.Name)" `
            -DefinitionName "$(Build.DefinitionName)" `
            -DefinitionVersion "$(Build.DefinitionVersion)"

          # New-CmAzIaasBastionHost -SettingsFile "$(Build.SourcesDirectory)/$(moduleName)/Resources/Project/bastionHost.yml" -Verbose
          # New-CmAzIaasVpnGw -SettingsFile "$(Build.SourcesDirectory)/$(moduleName)/Resources/Project/vpngw.yml" -Verbose

- stage: Security
  dependsOn: Core
  jobs:
  - job:
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: $(ServiceConnection)
        workingDirectory: $(Build.SourcesDirectory)
        pwsh: true
        errorActionPreference: Stop
        ScriptType: InlineScript
        FailOnStandardError: true
        azurePowerShellVersion: 'LatestVersion'
        Inline: |

          ./Initialise-Cloudmarque.ps1 `
            -ProjectDirectory "$(Build.SourcesDirectory)" `
            -Environment "$(environment)" `
            -BuildNumber "$(Build.BuildNumber)" `
            -RepositoryName "$(Build.Repository.Name)" `
            -DefinitionName "$(Build.DefinitionName)" `
            -DefinitionVersion "$(Build.DefinitionVersion)"

          Set-CmAzSecurityCentre -SettingsFile "$(Build.SourcesDirectory)/$(moduleName)/Resources/Project/security.yml" -Verbose

- stage: TearDown
  dependsOn: [
    "Iaas",
    "Paas",
    "Security"
  ]
  condition: always()
  displayName: Tear Down
  jobs:
  - job:
    steps:
     - task: AzurePowerShell@5
       inputs:
        azureSubscription: $(ServiceConnection)
        workingDirectory: $(Build.SourcesDirectory)
        pwsh: true
        errorActionPreference: Stop
        ScriptType: InlineScript
        FailOnStandardError: true
        azurePowerShellVersion: 'LatestVersion'
        Inline: |

          ./Initialise-Cloudmarque.ps1 `
            -ProjectDirectory "$(Build.SourcesDirectory)" `
            -Environment "$(environment)" `
            -BuildNumber "$(Build.BuildNumber)" `
            -RepositoryName "$(Build.Repository.Name)" `
            -DefinitionName "$(Build.DefinitionName)" `
            -DefinitionVersion "$(Build.DefinitionVersion)"

          Write-Verbose "Resetting security membership..."
          $resourceTypes = @("VirtualMachines", "AppServices", "SqlServers", "SqlServerVirtualMachines", "StorageAccounts", "KubernetesService", "ContainerRegistry", "KeyVaults")

          forEach ($resourceType in $resourceTypes) {
              Set-AzSecurityPricing -Name $resourceType -PricingTier "Free"
          }

          do {

            Write-Verbose "Removing tagged resources..."
            $errorThrown = $false

            Write-Verbose "Fetching resource groups.."
            $resources = Get-CmAzService -ServiceKey "cm-integration-test-delete" -Service "true" -IsResourceGroup -Verbose

            foreach ($resource in $resources) {

              try {
                Remove-AzResourceGroup -Name $resource.resourceGroupName -Verbose -Force
              }
              catch {
                $errorThrown = $true
              }
            }

          }
          while ($errorThrown)