component: automation                                           # Required to use settings with New-CmAzDeployment

service:
  dependencies:
    keyvault: Core-Test-Kv
    workspace: Core-Test-Ws
    vnet:
    privateZones: []
  publish:
    resourceGroup: Core-Test-Auto-Rg
    automation: Core-Test-Auto

automation:
  name: Core-Test-Auto042021
  location: UK South
  managedIdentity:
    enabled: true                                               # Default - True.
    scope:                                                      # Format - /subscriptions/<Sub id>
    role: Contributor                                           # Optional: Defaults to Contributor. Use "None" if no role should be assigned.
  sourceControl:
    keyVaultPersonalAccessToken:                                # Optional: (only if repoURL): keyvault secret name for PAT to access Repo.
    url:                                                        # Optional: For repo intergration.
    type:                                                       # Optional: (only if repoURL): github | git | tvfc.
    branch:                                                     # Optional: Branch to pull from. Not required for tvfc. Default is master.
    folderPath:                                                 # Optional: (only if repoURL): Path to folder which contains runbook or DSC files.
    service:
      dependencies:
        keyvault:
# privateEndpoints:
# - subnetName: Iaas-Test-Hub1-Vnet1-Snet-Dc1
#   name:                                                       # Defaults to resource name.
#   subResourceName: Webhook
#   service:
#     dependencies:
#       vnet: Iaas-Test-Hub1-Vnet1
#       privateZones:
#       - privatelink-automation
#     publish:
#       privateEndpoint: Auto-endpoint
# - subnetName: Iaas-Test-Hub1-Vnet1-Snet-Dc1
#   subResourceName: DSCAndHybridWorker
#   service:
#     dependencies:
#       vnet: Iaas-Test-Hub1-Vnet1
#       privateZones:
#       - privatelink-automation
#     publish:
#       privateEndpoint: Auto-endpoint

# Note - As automation account is deployed with core, private endpoints are deployed with privateendpoints.yml once IaaS dependencies are resolved.
# Note - Above option is available to be deployed after dependencies are deployed.